<a href="https://colab.research.google.com/github/ushasri0412/Data-Science-Task/blob/main/Data_cleaning_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

26-02-2026

 **DATA CLEANING TASK**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/USA_presidents.csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,S.No.,president,prior,party,vice,salary,date updated,date created
0,0,0,1,George Washington,Commander-in-Chief of the Continental Army ...,Nonpartisan,John Adams,NaN,2021-07-14,2012-03-04
1,1,1,2,john adams,1st Vice President of the United States,NaN,Thomas Jefferson,"$10,0,00",2021-07-14,2012-03-04
2,2,2,3,NaN,2nd Vice President of the United States,Democratic- Republican,Aaron Burr,NaN,2021-07-14,2012-03-04
3,3,3,4,James Madison,5th United States Secretary of State (1801â...,NaN,George Clinton,"$20,0,00",2021-07-14,NaN
4,4,4,5,NaN,7th United States Secretary of State (1811â...,Democratic- Republican,Daniel D. Tompkins,"$25,0,00",NaN,2012-03-04

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  47 non-null     int64
 1   Unnamed: 0    47 non-null     int64
 2   S.No.         47 non-null     int64
 3   president     45 non-null     object
 4   prior         47 non-null     object
 5   party         45 non-null     object
 6   vice          47 non-null     object
 7   salary        45 non-null     object
 8   date updated  46 non-null     object
 9   date created  46 non-null     object
dtypes: int64(3), object(7)
memory usage: 3.8+ KB

In [ ]:
df.isnull().sum()
df.dropna(inplace=True)
df.isnull().sum()

Unnamed: 0.1    0
Unnamed: 0      0
S.No.           0
president       0
prior           0
party           0
vice            0
salary          0
date updated    0
date created    0
dtype: int64

In [ ]:
df.shape
df.drop_duplicates(inplace=True)
df.shape

(42, 10)

In [ ]:
# df=df.drop("Unnamed: 0",axis=1)
# df
# df=df.drop("Unnamed: 0.1",axis=1)
# df
df=df.drop("S.No.",axis=1)
df

,Unnamed: 0.1,Unnamed: 0,president,prior,party,vice,salary,date updated,date created
5,5,5,John Quincy Adams,8th United States Secretary of State (1817â...,Democratic- Republican,John C. Calhoun,"$30,0,00",2021-07-14,2012-03-04
6,6,6,Andrew Jackson,U.S. Senator ( Class 2 ) from Tennessee ...,Democratic,John C. Calhoun,"$35,0,00",2021-07-14,2012-03-04
7,7,7,Martin Van Buren,8th Vice President of the United States,Democratic,Richard Mentor Johnson,"$40,0,00",2021-07-14,2012-03-04
8,8,8,William Henry Harrison,United States Minister to Colombia (1828â€“1...,Whig,John Tyler,"$45,0,00",2021-07-14,2012-03-04
9,9,9,john tyler,10th Vice President of the United States,"Whig April 4, 1841 â€“ September 13, 1841",Office vacant,"$50,0,00",2021-07-14,2012-03-04
10,10,10,James K. Polk,9th Governor of Tennessee (1839â€“1841),Democratic,George M. Dallas,"$55,0,00",2021-07-14,2012-03-04
11,11,11,Zachary Taylor,Major General of the 1st Infantry Regiment ...,Whig,Millard Fillmore,"$60,0,00",2021-07-14,2012-03-04
12,12,12,Millard Fillmore,12th Vice President of the United States,Whig,Office vacant,"$65,0,00",2021-07-14,2012-03-04
13,13,13,Franklin Pierce,Brigadier General of the 9th Infantry Unit...,Democratic,William R. King,"$75,0,00",2021-07-14,2012-03-04
14,14,14,James Buchanan,United States Minister to the Court of St J...,Democratic,John C. Breckinridge,"$85,0,00",2021-07-14,2012-03-04
15,15,15,Abraham Lincoln,U.S. Representative for Illinois' 7th Distri...,Republican,Hannibal Hamlin,"$95,0,00",2021-07-14,2012-03-04
16,16,16,Andrew Johnson,16th Vice President of the United States,Democratic,Office vacant,"$10,5,000",2021-07-14,2012-03-04
17,17,17,Ulysses S. Grant,Commanding General of the U.S. Army ( 1864â...,Republican,Schuyler Colfax,"$11,5,000",2021-07-14,2012-03-04
18,18,18,Rutherford B. Hayes,29th & 32nd Governor of Ohio (1868â€“1872 &...,Republican,William A. Wheeler,"$12,5,000",2021-07-14,2012-03-04
19,19,19,James A. Garfield,U.S. Representative for Ohio's 19th District...,Republican,Chester A. Arthur,"$13,5,000",2021-07-14,2012-03-04
20,20,20,Chester A. Arthur,20th Vice President of the United States,Republican,Office vacant,"$14,5,000",2021-07-14,2012-03-04
21,21,21,Grover Cleveland,28th Governor of New York (1883â€“1885),Democratic,Thomas A. Hendricks,"$15,5,000",2021-07-14,2012-03-04
22,22,22,Benjamin Harrison,U.S. Senator ( Class 1 ) from Indiana (...,Republican,Levi P. Morton,"$16,5,000",2021-07-14,2012-03-04
23,23,23,Grover Cleveland,22nd President of the United States (1885â€...,Democratic,Adlai Stevenson,"$17,5,000",2021-07-14,2012-03-04
24,24,24,William McKinley,39th Governor of Ohio (1892â€“1896),Republican,Garret Hobart,"$18,5,000",2021-07-14,2012-03-04
25,25,25,Theodore Roosevelt,25th Vice President of the United States,Republican,Office vacant,"$19,5,000",2021-07-14,2012-03-04
26,26,26,William Howard Taft,42nd United States Secretary of War (1904â€...,Republican,James S. Sherman,"$20,5,000",2021-07-14,2012-03-04
27,27,27,Woodrow Wilson,34th Governor of New Jersey (1911â€“1913),Democratic,Thomas R. Marshall,"$22,5,000",2021-07-14,2012-03-04
28,28,27,Woodrow Wilson,34th Governor of New Jersey (1911â€“1913),Demorcatic,Thomas R. Marshall,"$22,5,000",2021-07-14,2012-03-04
29,29,28,Warren G. Harding,U.S. Senator ( Class 3 ) from Ohio (191...,Republican,Calvin Coolidge,"$23,5,000",2021-07-14,2012-03-04
30,30,29,Calvin Coolidge,29th Vice President of the United States,Republican,Office vacant,"$24,5,000",2021-07-14,2012-03-04
31,31,30,Herbert Hoover,3rd United States Secretary of Commerce (19...,Republican,Charles Curtis,"$25,5,000",2021-07-14,2012-03-04
32,32,31,Franklin D. Roosevelt,44th Governor of New York ( 1929â€“1932 ),Democratic,John Nance Garner,"$26,5,000",2021-07-14,2012-03-04
33,33,32,Harry S. Truman,34th Vice President of the United States,Democratic,Office vacant,"$27,5,000",2021-07-14,2012-03-04
34,34,33,Dwight D. Eisenhower,Supreme Allied Commander Europe ( 1949â€“1952 ),Republican,Richard Nixon,"$28,5,000",2021-07-14,2012-03-04
35,35,34,John F. Kennedy,U.S. Senator ( Class 1 ) from Massachuset...,Democratic,Lyndon B. Johnson,"$29,5,000",2021-07-14,2012-03-04
36,36,35,Lyndon B. Johnson,37th Vice President of the United States,Democratic,Office vacant,"$30,5,000",2021-07-14,2012-03-04
37,37,36,Richard Nixon,36th Vice President of the United States (1...,Republican,Spiro Agnew,"$31,5,000",2021-07-14,2012-03-04
38,38,37,Gerald Ford,40th Vice President of the United States,Republican,Office vacant,"$32,5,000",2021-07-14,2012-03-04
39,39,38,Jimmy Carter,76th Governor of Georgia (1971â€“1975),Democratic,Walter Mondale,"$33,5,000",2021-07-14,2012-03-04
40,40,39,Ronald Reagan,33rd Governor of California ( 1967â€“1975 ),Republican,George H. W. Bush,"$34,5,000",2021-07-14,2012-03-04
41,41,40,George H. W. Bush,43rd Vice President of the United States,Republican,Dan Quayle,"$35,5,000",2021-07-14,2012-03-04
42,42,41,Bill Clinton,40th & 42nd Governor of Arkansas (1979â€“19...,Democratic,Al Gore,"$36,5,000",2021-07-14,2012-03-04
43,43,42,George W. Bush,46th Governor of Texas ( 1995â€“2000 ),Republican,Dick Cheney,"$37,5,000",2021-07-14,2012-03-04
44,44,43,Barack Obama,U.S. Senator ( Class 3 ) from Illinois ...,Democratic,Joe Biden,"$39,5,000",2021-07-14,2020-02-01
45,45,43,Barack Obama,U.S. Senator ( Class 3 ) from Illinois ...,Democratic,Joe Biden,"$39,5,000",2021-07-14,2020-02-01
46,46,44,Donald Trump,Chairman of The Trump Organization ( 1971â...,Republicans,Mike Pence,"$40,5,000",2021-07-14,2020-02-01

In [ ]:
df["president"].unique()

array(['John Quincy Adams', 'Andrew Jackson', 'Martin Van Buren',
       'William Henry Harrison', 'john tyler', 'James K. Polk',
       'Zachary Taylor', 'Millard Fillmore', 'Franklin Pierce',
       'James Buchanan', 'Abraham Lincoln', 'Andrew Johnson',
       'Ulysses S. Grant', 'Rutherford B. Hayes', 'James A. Garfield',
       'Chester A. Arthur', 'Grover Cleveland', 'Benjamin Harrison',
       'William McKinley', 'Theodore Roosevelt', 'William Howard Taft',
       'Woodrow Wilson', 'Warren G. Harding', 'Calvin Coolidge',
       'Herbert Hoover', 'Franklin D. Roosevelt', 'Harry S. Truman',
       'Dwight D. Eisenhower', 'John F. Kennedy', 'Lyndon B. Johnson',
       'Richard Nixon', 'Gerald Ford', 'Jimmy Carter', 'Ronald Reagan',
       'George H. W. Bush', 'Bill Clinton', 'George W. Bush',
       'Barack Obama', 'Donald Trump'], dtype=object)

In [ ]:
df["prior"].unique()

array(['8th  United States Secretary of State   (1817â€“1825)',
       'U.S. Senator   ( Class 2 )   from  Tennessee   (1823â€“1825)',
       '8th  Vice President of the United States',
       'United States Minister to Colombia   (1828â€“1829)',
       '10th  Vice President of the United States',
       '9th  Governor of Tennessee   (1839â€“1841)',
       'Major General  of the  1st Infantry Regiment   United States Army   (1846â€“1849)',
       '12th  Vice President of the United States',
       'Brigadier General  of the  9th Infantry   United States Army   (1847â€“1848)',
       "United States Minister  to the   Court of St James's   (1853â€“1856)",
       "U.S. Representative  for  Illinois' 7th District   (1847â€“1849)",
       '16th  Vice President of the United States',
       'Commanding General  of the U.S. Army   ( 1864â€“1869 )',
       '29th & 32nd  Governor of Ohio   (1868â€“1872 & 1876â€“1877)',
       "U.S. Representative  for  Ohio's 19th District   (1863â€“1881)",
       '20th  Vice President of the United States',
       '28th  Governor of New York   (1883â€“1885)',
       'U.S. Senator   ( Class 1 )   from  Indiana   (1881â€“1887)',
       '22nd  President of the United States   (1885â€“1889)',
       '39th  Governor of Ohio   (1892â€“1896)',
       '25th  Vice President of the United States',
       '42nd  United States Secretary of War   (1904â€“1908)',
       '34th  Governor of New Jersey   (1911â€“1913)',
       'U.S. Senator   ( Class 3 )   from  Ohio   (1915â€“1921)',
       '29th  Vice President of the United States',
       '3rd  United States Secretary of Commerce   (1921â€“1928)',
       '44th  Governor of New York   ( 1929â€“1932 )',
       '34th  Vice President of the United States',
       'Supreme Allied Commander Europe   ( 1949â€“1952 )',
       'U.S. Senator   ( Class 1 )   from  Massachusetts   (1953â€“1960)',
       '37th  Vice President of the United States',
       '36th  Vice President of the United States   (1953â€“1961)',
       '40th  Vice President of the United States',
       '76th  Governor of Georgia   (1971â€“1975)',
       '33rd  Governor of California   ( 1967â€“1975 )',
       '43rd  Vice President of the United States',
       '40th & 42nd  Governor of Arkansas   (1979â€“1981 & 1983â€“1992)',
       '46th  Governor of Texas   ( 1995â€“2000 )',
       'U.S. Senator   ( Class 3 )   from  Illinois   ( 2005â€“2008 )',
       'Chairman of   The Trump Organization   ( 1971â€“present )'],
      dtype=object)

In [ ]:
d={"president":"President Name","prior": "Priotity_position",	"party": "Party Type"	,"vice": "Vice President","salary" :"Salary","date updated": "Date Updated","date created" :"Date Created"}
df.rename(columns=d,inplace=True)
df

,Unnamed: 0.1,Unnamed: 0,President Name,Priotity_position,Party Type,Vice President,Salary,Date Updated,Date Created
5,5,5,John Quincy Adams,8th United States Secretary of State (1817â...,Democratic- Republican,John C. Calhoun,"$30,0,00",2021-07-14,2012-03-04
6,6,6,Andrew Jackson,U.S. Senator ( Class 2 ) from Tennessee ...,Democratic,John C. Calhoun,"$35,0,00",2021-07-14,2012-03-04
7,7,7,Martin Van Buren,8th Vice President of the United States,Democratic,Richard Mentor Johnson,"$40,0,00",2021-07-14,2012-03-04
8,8,8,William Henry Harrison,United States Minister to Colombia (1828â€“1...,Whig,John Tyler,"$45,0,00",2021-07-14,2012-03-04
9,9,9,john tyler,10th Vice President of the United States,"Whig April 4, 1841 â€“ September 13, 1841",Office vacant,"$50,0,00",2021-07-14,2012-03-04
10,10,10,James K. Polk,9th Governor of Tennessee (1839â€“1841),Democratic,George M. Dallas,"$55,0,00",2021-07-14,2012-03-04
11,11,11,Zachary Taylor,Major General of the 1st Infantry Regiment ...,Whig,Millard Fillmore,"$60,0,00",2021-07-14,2012-03-04
12,12,12,Millard Fillmore,12th Vice President of the United States,Whig,Office vacant,"$65,0,00",2021-07-14,2012-03-04
13,13,13,Franklin Pierce,Brigadier General of the 9th Infantry Unit...,Democratic,William R. King,"$75,0,00",2021-07-14,2012-03-04
14,14,14,James Buchanan,United States Minister to the Court of St J...,Democratic,John C. Breckinridge,"$85,0,00",2021-07-14,2012-03-04
15,15,15,Abraham Lincoln,U.S. Representative for Illinois' 7th Distri...,Republican,Hannibal Hamlin,"$95,0,00",2021-07-14,2012-03-04
16,16,16,Andrew Johnson,16th Vice President of the United States,Democratic,Office vacant,"$10,5,000",2021-07-14,2012-03-04
17,17,17,Ulysses S. Grant,Commanding General of the U.S. Army ( 1864â...,Republican,Schuyler Colfax,"$11,5,000",2021-07-14,2012-03-04
18,18,18,Rutherford B. Hayes,29th & 32nd Governor of Ohio (1868â€“1872 &...,Republican,William A. Wheeler,"$12,5,000",2021-07-14,2012-03-04
19,19,19,James A. Garfield,U.S. Representative for Ohio's 19th District...,Republican,Chester A. Arthur,"$13,5,000",2021-07-14,2012-03-04
20,20,20,Chester A. Arthur,20th Vice President of the United States,Republican,Office vacant,"$14,5,000",2021-07-14,2012-03-04
21,21,21,Grover Cleveland,28th Governor of New York (1883â€“1885),Democratic,Thomas A. Hendricks,"$15,5,000",2021-07-14,2012-03-04
22,22,22,Benjamin Harrison,U.S. Senator ( Class 1 ) from Indiana (...,Republican,Levi P. Morton,"$16,5,000",2021-07-14,2012-03-04
23,23,23,Grover Cleveland,22nd President of the United States (1885â€...,Democratic,Adlai Stevenson,"$17,5,000",2021-07-14,2012-03-04
24,24,24,William McKinley,39th Governor of Ohio (1892â€“1896),Republican,Garret Hobart,"$18,5,000",2021-07-14,2012-03-04
25,25,25,Theodore Roosevelt,25th Vice President of the United States,Republican,Office vacant,"$19,5,000",2021-07-14,2012-03-04
26,26,26,William Howard Taft,42nd United States Secretary of War (1904â€...,Republican,James S. Sherman,"$20,5,000",2021-07-14,2012-03-04
27,27,27,Woodrow Wilson,34th Governor of New Jersey (1911â€“1913),Democratic,Thomas R. Marshall,"$22,5,000",2021-07-14,2012-03-04
28,28,27,Woodrow Wilson,34th Governor of New Jersey (1911â€“1913),Demorcatic,Thomas R. Marshall,"$22,5,000",2021-07-14,2012-03-04
29,29,28,Warren G. Harding,U.S. Senator ( Class 3 ) from Ohio (191...,Republican,Calvin Coolidge,"$23,5,000",2021-07-14,2012-03-04
30,30,29,Calvin Coolidge,29th Vice President of the United States,Republican,Office vacant,"$24,5,000",2021-07-14,2012-03-04
31,31,30,Herbert Hoover,3rd United States Secretary of Commerce (19...,Republican,Charles Curtis,"$25,5,000",2021-07-14,2012-03-04
32,32,31,Franklin D. Roosevelt,44th Governor of New York ( 1929â€“1932 ),Democratic,John Nance Garner,"$26,5,000",2021-07-14,2012-03-04
33,33,32,Harry S. Truman,34th Vice President of the United States,Democratic,Office vacant,"$27,5,000",2021-07-14,2012-03-04
34,34,33,Dwight D. Eisenhower,Supreme Allied Commander Europe ( 1949â€“1952 ),Republican,Richard Nixon,"$28,5,000",2021-07-14,2012-03-04
35,35,34,John F. Kennedy,U.S. Senator ( Class 1 ) from Massachuset...,Democratic,Lyndon B. Johnson,"$29,5,000",2021-07-14,2012-03-04
36,36,35,Lyndon B. Johnson,37th Vice President of the United States,Democratic,Office vacant,"$30,5,000",2021-07-14,2012-03-04
37,37,36,Richard Nixon,36th Vice President of the United States (1...,Republican,Spiro Agnew,"$31,5,000",2021-07-14,2012-03-04
38,38,37,Gerald Ford,40th Vice President of the United States,Republican,Office vacant,"$32,5,000",2021-07-14,2012-03-04
39,39,38,Jimmy Carter,76th Governor of Georgia (1971â€“1975),Democratic,Walter Mondale,"$33,5,000",2021-07-14,2012-03-04
40,40,39,Ronald Reagan,33rd Governor of California ( 1967â€“1975 ),Republican,George H. W. Bush,"$34,5,000",2021-07-14,2012-03-04
41,41,40,George H. W. Bush,43rd Vice President of the United States,Republican,Dan Quayle,"$35,5,000",2021-07-14,2012-03-04
42,42,41,Bill Clinton,40th & 42nd Governor of Arkansas (1979â€“19...,Democratic,Al Gore,"$36,5,000",2021-07-14,2012-03-04
43,43,42,George W. Bush,46th Governor of Texas ( 1995â€“2000 ),Republican,Dick Cheney,"$37,5,000",2021-07-14,2012-03-04
44,44,43,Barack Obama,U.S. Senator ( Class 3 ) from Illinois ...,Democratic,Joe Biden,"$39,5,000",2021-07-14,2020-02-01
45,45,43,Barack Obama,U.S. Senator ( Class 3 ) from Illinois ...,Democratic,Joe Biden,"$39,5,000",2021-07-14,2020-02-01
46,46,44,Donald Trump,Chairman of The Trump Organization ( 1971â...,Republicans,Mike Pence,"$40,5,000",2021-07-14,2020-02-01

In [ ]:
df["Priotity_position"] = df["Priotity_position"].str.replace("â€“", "-")
df["Priotity_position"].unique()

array(['8th  United States Secretary of State   (1817-1825)',
       'U.S. Senator   ( Class 2 )   from  Tennessee   (1823-1825)',
       '8th  Vice President of the United States',
       'United States Minister to Colombia   (1828-1829)',
       '10th  Vice President of the United States',
       '9th  Governor of Tennessee   (1839-1841)',
       'Major General  of the  1st Infantry Regiment   United States Army   (1846-1849)',
       '12th  Vice President of the United States',
       'Brigadier General  of the  9th Infantry   United States Army   (1847-1848)',
       "United States Minister  to the   Court of St James's   (1853-1856)",
       "U.S. Representative  for  Illinois' 7th District   (1847-1849)",
       '16th  Vice President of the United States',
       'Commanding General  of the U.S. Army   ( 1864-1869 )',
       '29th & 32nd  Governor of Ohio   (1868-1872 & 1876-1877)',
       "U.S. Representative  for  Ohio's 19th District   (1863-1881)",
       '20th  Vice President of the United States',
       '28th  Governor of New York   (1883-1885)',
       'U.S. Senator   ( Class 1 )   from  Indiana   (1881-1887)',
       '22nd  President of the United States   (1885-1889)',
       '39th  Governor of Ohio   (1892-1896)',
       '25th  Vice President of the United States',
       '42nd  United States Secretary of War   (1904-1908)',
       '34th  Governor of New Jersey   (1911-1913)',
       'U.S. Senator   ( Class 3 )   from  Ohio   (1915-1921)',
       '29th  Vice President of the United States',
       '3rd  United States Secretary of Commerce   (1921-1928)',
       '44th  Governor of New York   ( 1929-1932 )',
       '34th  Vice President of the United States',
       'Supreme Allied Commander Europe   ( 1949-1952 )',
       'U.S. Senator   ( Class 1 )   from  Massachusetts   (1953-1960)',
       '37th  Vice President of the United States',
       '36th  Vice President of the United States   (1953-1961)',
       '40th  Vice President of the United States',
       '76th  Governor of Georgia   (1971-1975)',
       '33rd  Governor of California   ( 1967-1975 )',
       '43rd  Vice President of the United States',
       '40th & 42nd  Governor of Arkansas   (1979-1981 & 1983-1992)',
       '46th  Governor of Texas   ( 1995-2000 )',
       'U.S. Senator   ( Class 3 )   from  Illinois   ( 2005-2008 )',
       'Chairman of   The Trump Organization   ( 1971-present )'],
      dtype=object)

In [ ]:
df["Party Type"].unique()

array(['Democratic-  Republican', 'Democratic', 'Whig',
       'Whig   April 4, 1841  â€“  September 13, 1841', 'Republican',
       'Demorcatic', 'Republicans'], dtype=object)

In [ ]:
df["Party Type"]=df["Party Type"].str.strip("   April 4, 1841  â€“  September 13, 1841")
df["Party Type"].unique()

array(['Democratic-  Republican', 'Democratic', 'Whig', 'Republican',
       'Demorcatic', 'Republicans'], dtype=object)

In [ ]:
df["Party Type"] = df["Party Type"].str.replace("Republicans", "Republican")
df["Party Type"].unique()

array(['Democratic-  Republican', 'Democratic', 'Whig', 'Republican',
       'Demorcatic'], dtype=object)

In [ ]:
df["Party Type"] = df["Party Type"].str.replace("Demorcatic", "Democratic")
df["Party Type"].unique()

array(['Democratic-  Republican', 'Democratic', 'Whig', 'Republican'],
      dtype=object)

In [ ]:
df["Party Type"] = df["Party Type"].str.replace("Democratic-  Republican", "Democratic-Republican")
df["Party Type"].unique()

array(['Democratic-Republican', 'Democratic', 'Whig', 'Republican'],
      dtype=object)

In [ ]:
df["Vice President"].unique()

array(['John C. Calhoun', 'John C.     Calhoun', 'Richard Mentor Johnson',
       'John Tyler', 'Office vacant', 'George         M. Dallas',
       '               Millard Fillmore', 'William R. King',
       'John C. Breckinridge', 'Hannibal Hamlin', 'Schuyler Colfax',
       'William A. Wheeler', 'Chester A. Arthur', 'Thomas A. Hendricks',
       'Levi P. Morton', 'Adlai Stevenson', 'Garret Hobart',
       'James S. Sherman', 'Thomas R. Marshall', 'Calvin Coolidge',
       'Charles Curtis', 'John Nance Garner', 'Richard Nixon',
       'Lyndon B. Johnson', 'Spiro Agnew', 'Walter Mondale',
       'George H. W. Bush', 'Dan Quayle', 'Al Gore', 'Dick Cheney',
       'Joe Biden', 'Mike Pence'], dtype=object)

In [ ]:
df["Vice President"]=df["Vice President"].str.strip("     ")
df["Vice President"].unique()

array(['John C. Calhoun', 'John C.     Calhoun', 'Richard Mentor Johnson',
       'John Tyler', 'Office vacant', 'George         M. Dallas',
       'Millard Fillmore', 'William R. King', 'John C. Breckinridge',
       'Hannibal Hamlin', 'Schuyler Colfax', 'William A. Wheeler',
       'Chester A. Arthur', 'Thomas A. Hendricks', 'Levi P. Morton',
       'Adlai Stevenson', 'Garret Hobart', 'James S. Sherman',
       'Thomas R. Marshall', 'Calvin Coolidge', 'Charles Curtis',
       'John Nance Garner', 'Richard Nixon', 'Lyndon B. Johnson',
       'Spiro Agnew', 'Walter Mondale', 'George H. W. Bush', 'Dan Quayle',
       'Al Gore', 'Dick Cheney', 'Joe Biden', 'Mike Pence'], dtype=object)

In [ ]:
df["Vice President"]=df["Vice President"].str.replace("John C.     Calhoun","John C.Calhoun")
df["Vice President"].unique()

array(['John C. Calhoun', 'John C.Calhoun', 'Richard Mentor Johnson',
       'John Tyler', 'Office vacant', 'George         M. Dallas',
       'Millard Fillmore', 'William R. King', 'John C. Breckinridge',
       'Hannibal Hamlin', 'Schuyler Colfax', 'William A. Wheeler',
       'Chester A. Arthur', 'Thomas A. Hendricks', 'Levi P. Morton',
       'Adlai Stevenson', 'Garret Hobart', 'James S. Sherman',
       'Thomas R. Marshall', 'Calvin Coolidge', 'Charles Curtis',
       'John Nance Garner', 'Richard Nixon', 'Lyndon B. Johnson',
       'Spiro Agnew', 'Walter Mondale', 'George H. W. Bush', 'Dan Quayle',
       'Al Gore', 'Dick Cheney', 'Joe Biden', 'Mike Pence'], dtype=object)

In [ ]:
df["Vice President"]=df["Vice President"].str.replace("John C. Calhoun","John C.Calhoun")
df["Vice President"].unique()

array(['John C.Calhoun', 'Richard Mentor Johnson', 'John Tyler',
       'Office vacant', 'George         M. Dallas', 'Millard Fillmore',
       'William R. King', 'John C. Breckinridge', 'Hannibal Hamlin',
       'Schuyler Colfax', 'William A. Wheeler', 'Chester A. Arthur',
       'Thomas A. Hendricks', 'Levi P. Morton', 'Adlai Stevenson',
       'Garret Hobart', 'James S. Sherman', 'Thomas R. Marshall',
       'Calvin Coolidge', 'Charles Curtis', 'John Nance Garner',
       'Richard Nixon', 'Lyndon B. Johnson', 'Spiro Agnew',
       'Walter Mondale', 'George H. W. Bush', 'Dan Quayle', 'Al Gore',
       'Dick Cheney', 'Joe Biden', 'Mike Pence'], dtype=object)

In [ ]:
df["Vice President"]=df["Vice President"].str.replace("George         M. Dallas","George M. Dallas")
df["Vice President"].unique()

array(['John C.Calhoun', 'Richard Mentor Johnson', 'John Tyler',
       'Office vacant', 'George M. Dallas', 'Millard Fillmore',
       'William R. King', 'John C. Breckinridge', 'Hannibal Hamlin',
       'Schuyler Colfax', 'William A. Wheeler', 'Chester A. Arthur',
       'Thomas A. Hendricks', 'Levi P. Morton', 'Adlai Stevenson',
       'Garret Hobart', 'James S. Sherman', 'Thomas R. Marshall',
       'Calvin Coolidge', 'Charles Curtis', 'John Nance Garner',
       'Richard Nixon', 'Lyndon B. Johnson', 'Spiro Agnew',
       'Walter Mondale', 'George H. W. Bush', 'Dan Quayle', 'Al Gore',
       'Dick Cheney', 'Joe Biden', 'Mike Pence'], dtype=object)

In [ ]:
df["Salary"].unique()

array(['$30,0,00', '$35,0,00', '$40,0,00', '$45,0,00', '$50,0,00',
       '$55,0,00', '$60,0,00', '$65,0,00', '$75,0,00', '$85,0,00',
       '$95,0,00', '$10,5,000', '$11,5,000', '$12,5,000', '$13,5,000',
       '$14,5,000', '$15,5,000', '$16,5,000', '$17,5,000', '$18,5,000',
       '$19,5,000', '$20,5,000', '$22,5,000', '$23,5,000', '$24,5,000',
       '$25,5,000', '$26,5,000', '$27,5,000', '$28,5,000', '$29,5,000',
       '$30,5,000', '$31,5,000', '$32,5,000', '$33,5,000', '$34,5,000',
       '$35,5,000', '$36,5,000', '$37,5,000', '$39,5,000', '$40,5,000'],
      dtype=object)

In [ ]:
df["Salary"]=df["Salary"].str.strip("$")
df["Salary"].unique()

array(['30,0,00', '35,0,00', '40,0,00', '45,0,00', '50,0,00', '55,0,00',
       '60,0,00', '65,0,00', '75,0,00', '85,0,00', '95,0,00', '10,5,000',
       '11,5,000', '12,5,000', '13,5,000', '14,5,000', '15,5,000',
       '16,5,000', '17,5,000', '18,5,000', '19,5,000', '20,5,000',
       '22,5,000', '23,5,000', '24,5,000', '25,5,000', '26,5,000',
       '27,5,000', '28,5,000', '29,5,000', '30,5,000', '31,5,000',
       '32,5,000', '33,5,000', '34,5,000', '35,5,000', '36,5,000',
       '37,5,000', '39,5,000', '40,5,000'], dtype=object)

In [ ]:
df["Salary"]=df["Salary"].str.replace(",","")
df["Salary"].unique()

array(['30000', '35000', '40000', '45000', '50000', '55000', '60000',
       '65000', '75000', '85000', '95000', '105000', '115000', '125000',
       '135000', '145000', '155000', '165000', '175000', '185000',
       '195000', '205000', '225000', '235000', '245000', '255000',
       '265000', '275000', '285000', '295000', '305000', '315000',
       '325000', '335000', '345000', '355000', '365000', '375000',
       '395000', '405000'], dtype=object)

In [ ]:
df["Salary"]=df["Salary"].astype(float)
df["Salary"]=df["Salary"].astype(int)
df["Salary"].unique()

array([ 30000,  35000,  40000,  45000,  50000,  55000,  60000,  65000,
        75000,  85000,  95000, 105000, 115000, 125000, 135000, 145000,
       155000, 165000, 175000, 185000, 195000, 205000, 225000, 235000,
       245000, 255000, 265000, 275000, 285000, 295000, 305000, 315000,
       325000, 335000, 345000, 355000, 365000, 375000, 395000, 405000])

In [ ]:
df["Date Updated"].unique()

array(['2021-07-14'], dtype=object)